list: $/rezokretien/music/models/music/columns.yaml
modelClass: Rezokretien\Music\Models\Music
title: Music
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'rezokretien/music/music/update/:id'
