list: $/rezokretien/event/models/event/columns.yaml
modelClass: Rezokretien\Event\Models\Event
title: Event
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'rezokretien/event/event/update/:id'
