list: $/rezokretien/preche/models/preche/columns.yaml
modelClass: Rezokretien\Preche\Models\Preche
title: Preche
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'rezokretien/preche/preche/update/:id'
